### ISSUE TITLE
GPU usage unclear

### ISSUE THREAD

**Issue by ebachUTSA** [umbertogriffo/rag-chatbot#5]
I've been playing around with a version of your repo (very nice btw). However, when monitoring execution it does not appear this is using the GPU for offloading (I'm not seeing any increased GPU activity in monitoring). There are no errors, CUDA is installed and all dependencies that are necessary for CUDA are present.

Looks like when testing on a windows environment, the nvidia-nccl-cu12 package is not available (NCCL is not available on windows).

EDIT (June 20, 2024):
Disregard the above. Due to not having done this on a windows system before I had to figure out a few differences with how you set up llama compiled resources (specifically llama-cpp-python). Unfortunately compounding issues in the process took a good long while to figure out (and a lot of cmake log inspection). Takeaways for anyone trying to install locall llm support on windows via llama-cpp-python:

before running cmake, make sure you set the following two environment variables:

set CMAKE_ARGS="-DLLAMA_CUBLAS=on"
set FORCE_CMAKE=1

or, if you are using terminal/powershell, then:

$env:CMAKE_ARGS="-DLLAMA_CUBLAS=on"
$env:FORCE_CMAKE=1

For those curious, my issue was my build script neglected the quotes on the set version. I only realized the difference when running it from terminal/powershell that the powershell version had quotes. That was the only difference I could find between unsuccessful compilations with CUDA and the one that worked.

**Comment by umbertogriffo** [comment]
Hi @ebachUTSA! Thanks for opening this issue and figuring out a solution for Windows.
Unfortunately, I've never tried running the chatbot on Windows, and it needs some adaptations.
It would be great if you would open a PR to make it work on Windows :smile:
